### ISSUE TITLE
Docs: Tables misformatted in ReadTheDocs

### ISSUE THREAD

**Issue by akshayjshah** [uber/tchannel#1015]
For some reason, GitHub's reStructuredText parser handles our table markup just fine (e.g., https://github.com/uber/tchannel/blob/master/docs/protocol.md#type1), but ReadTheDocs doesn't (e.g., http://tchannel.readthedocs.org/en/latest/protocol.html#type-1).

This isn't a huge deal, but it does make reading the protocol specification difficult on RtD.

**Comment by blampe** [comment]
Fixed in #1063.
