### ISSUE TITLE
Travis CI / coveralls strategy?

### ISSUE THREAD

**Issue by sectioneight** [uber/tchannel#109]
I have Travis/Coveralls set up nicely for the tchannel.py repo. I think we can get travis to do the Right Thing here by running all the tests for every PR, but I'm less clear about coveralls. Should we just turn off coveralls? Or try to merge the two coverage reports together?

**Comment by Raynos** [comment]
I'd be good to have two travis projects somehow. Or at least have two build statuses.

**Comment by sectioneight** [comment]
I'm not super familiar with how/if that would work. I think to start we should just get a top-level .travis.yml file and populate it with the bits to run a Node test job and a Python test job.

https://github.com/travis-ci/travis-ci/issues/538

**Comment by Raynos** [comment]
sounds good to me.

**Comment by sectioneight** [comment]
Cool. The Python stuff is up and running.
