### ISSUE TITLE
Provide ability to register callback when any Thrift request arrives

### ISSUE THREAD

**Issue by cjbradfield** [uber/tchannel#1131]
Use case: I have some sort of per-client service context I need to look up.  Rather than have the same lookup/creation code in every thrift handler function, it would be nice to be able to register something that does that lookup regardless of the handler function name first and then provides the result in the thrift.Context or or some other argument to the function.

**Comment by prashantv** [comment]
I like the idea of registering middleware that lets you modify the context, maybe something like
```go
type Handler func(ctx thrift.Context, method string, call *tchannel.IncomingCall)
type Middleware func (ctx thrift.Context, method string, call *tchannel.IncomingCall, nextHandler Handler)

func (s *Server) AddMiddleware(Middleware middleware)

```

**Comment by prashantv** [comment]
Migrated to https://github.com/uber/tchannel-go/issues/123
