### ISSUE TITLE
node crc module should use SSE42 version

### ISSUE THREAD

**Issue by mranney** [uber/tchannel#118]
Modern Intel CPUs have instructions for computing CRC32. We should use them:

https://www.npmjs.com/package/sse4_crc32

**Comment by jcorbin** [comment]
It's not clear from the README that it presents a function(data, prior) to
support our chaining needs? I hope that's just a README oversight.

**Comment by mranney** [comment]
Yes, total readme fail. The second arg is the "prior" value:

```
mjr-uber-mbp:~$ node
> var c = 0;
undefined
> c = require("sse4_crc32").calculate("foo", c)
3485773341
> c = require("sse4_crc32").calculate("bar", c)
224353407
> c
224353407
```

**Comment by mranney** [comment]
FIxed: https://github.com/Voxer/sse4_crc32/commit/0ac8a858e2fd17e645d7aedf1a35885d5389b18f

**Comment by jcorbin** [comment]
As mentioned in #230, I did a brief try to use this:
- it didn't seem to have hardware support on my MBP
- the software version returned a wrong result

This was from all of ~5 minute of trying one example tho mind.

**Comment by Raynos** [comment]
We now support crc32
