### ISSUE TITLE
Thrift example ---> error

### ISSUE THREAD

**Issue by tsw424** [uber/tchannel#1199]
this page :  https://github.com/uber/tchannel/blob/master/node/docs/as-thrift.md 

       throw errors.TopLevelRequestError();
                     ^
TchannelTopLevelRequestError: Cannot make request() on top level tchannel.

**Comment by kriskowal** [comment]
Fixing this now, over in the separate tchannel-node repository. The usage has drifted somewhat.

https://github.com/uber/tchannel-node/pull/29
