### ISSUE TITLE
Cut node 2.0.0

### ISSUE THREAD

**Issue by jcorbin** [uber/tchannel#122]
Current blockers (2015-04-28):
- [x] finalize MIGRATION guide
- [ ] ~~circuit breaking model~~
- [x] complete, if minimal, protocol implementation
  - [x] ping
  - [x] claim
  - [x] cancel
  - [x] init handshake blocks call req (no init+call pipelining)
- [x] protocol errata
  - [x] arg1 shouldn't be fragmented or streamed
  - [x] limit allowed total overhead of a call req frame, currently it's nearly 2x max frame size, leaving no room for arg 1 (current max size is 0x1ff23 bytes, aka (128Ki - 221)B

**Comment by Raynos** [comment]
Possible breaking changes up for grabs:

 - [ ] make `opts.span` required in `tchannel.request()`
 - [ ] make `opts.inreq` required in `tchannel.request()`
 - [ ] change `nameAsThrift` from field on err to field on ThriftResponse
 - [ ] consider making `.request()` and `.register()` fail on the top channel; there has been confusion recently around whether you should use the topChannel or a subChannel ( we always want to use sub channels ).

**Comment by jcorbin** [comment]
re: client libraries and multiple copies, can we not just inject a `tchannelAsThrift` instance?

**Comment by Raynos** [comment]
We have consensus that the "cn" header is required.

We have consensus that the "as" header is required.

**Comment by Raynos** [comment]
We should encourage libraries to never depend on `tchannel` and to take a `TChannelAsThrift` constructor.

**Comment by Raynos** [comment]
All the features for 2.0.0 are in;

There are only four **BLOCKERS** left

 - [ ] update the README with documentation.
 - [ ] write a quick node guide
 - [ ] update the MIGRATION guide
 - [ ] get all the examples operational again.

**Comment by Raynos** [comment]
That's it. 2.0.0 we are done.
