### ISSUE TITLE
go: Simplify Meta service endpoint registration

### ISSUE THREAD

**Issue by prashantv** [uber/tchannel#1288]
Design interface for services to easily register a Meta endpoint - they should only need to specify a function that returns a HealthResult.

**Comment by xinlaini** [comment]
+1, ideally, the thrift service implementer should be able to opt-out explicit health check handling by allowing the default handler to return OK.

IMO TChannel library should provide a default implementation of meta endpoints like health check. If the thrift service wants, they can provide an optional handler to override the default behavior, but they shouldn't be burdened with implementing the meta endpoints.

**Comment by Raynos** [comment]
This is implemented in node. ( https://github.com/uber/tchannel/blob/master/node/as/thrift.js#L63-L71 ).

We should also get this implemented in python.
