### ISSUE TITLE
Cannot npm install from git repo

### ISSUE THREAD

**Issue by malandrew** [uber/tchannel#132]
Since uber/tchannel contains both the node and python implementations and the node implementation and it's package.json is a in a subfolder, it's currently not possible to install from the git+ssh url. Two ways to fix this: (1) split the python and nodejs implementations into two separate repos, (2) move package.json to the root folder.

I reckon this is something that is planned, but just hasn't been done yet as the v2 protocol is finalized.

**Comment by jcorbin** [comment]
Yes it's planned and accounted for:

1. we have a dev_node branch which we publish subtrees into from master

So just `npm install uber/tchannel#dev_node` for latest greatest (as late as whenever someone remembered to run `make -C node update_dev` that is).

2. We're also cutting alpha release tags

Less frequently than we update `dev_node` even, we're publishing `2.0.0-alphaN` for use in production prototype services (this is how autobahn, dispatch, and ncar are currently doing it).

In this case an `npm install tchannel@alpha` or pick a specific alpha with `npm install tchannel@2.0.0-alpha1`.

**Comment by Raynos** [comment]
There is still an open issue of how to do development.

The current working tree of `tchannel` does not easily allow for `npm link` or equivelant tooling when wanting to develop / test / iterate on `tchannel` within an application.

**Comment by Raynos** [comment]
However the use case for "how do I use a feature branch or fixed tag" is solved with the tooling in our Makefile.

**Comment by Raynos** [comment]
lol. `npm link` actually works. i just didnt think it through.

The thing that does not work is the hackish abbreviation of `npm link` that is called "keep reinstalling your git branch"
