### ISSUE TITLE
Why does the error frame have an `id:4` in the body?

### ISSUE THREAD

**Issue by Raynos** [uber/tchannel#166]
There appears to be an `id` in the error frame; both in the frame id and the body id.

Not sure why that is.

cc @mranney

**Comment by breerly** [comment]
@Raynos this still an issue?

**Comment by Raynos** [comment]
I think its fixed.

**Comment by jcorbin** [comment]
actually it's not been fixed yet, just tossed out #261 to get the ball rolling
