### ISSUE TITLE
Node throw if serviceName is not set.

### ISSUE THREAD

**Issue by Raynos** [uber/tchannel#171]
Autobahn needs a serviceName to operate cleanly.

It would be nice if the `serviceName` field was required in call requests and call responses.

**Comment by jcorbin** [comment]
Yeah, I'd rather this not be a low level read/write error tho... something either at entry level (TChannel.request) or JIT on req.send / res.send seems right to me.

**Comment by Raynos** [comment]
Fair enough; seems #legit

**Comment by Raynos** [comment]
This is currently implemented in the as layers
