### ISSUE TITLE
ChunkWriter throws when it fails to write chunks.

### ISSUE THREAD

**Issue by Raynos** [uber/tchannel#172]
Failing to write `TChannelFrame` objects to the socket is probably an operational error and should not throw.

**Comment by jcorbin** [comment]
Please re-evaluate after #163 which drops the writer out of tchannel, and uses the one from bufrw directly.

**Comment by Raynos** [comment]
Will do.

**Comment by Raynos** [comment]
We audited all exceptions and handled them appropiately. Fixed.
