### ISSUE TITLE
node: Getting an error frame for a timed out operation

### ISSUE THREAD

**Issue by Raynos** [uber/tchannel#254]
There is a race where we either get two error frames or a timeout and an error frame.

This causes us to have an undefined `op` which is not handled nicely.

```
/home/raynos/uber/ncar-performance-test/node_modules/tchannel/index.js:506
        op.req.emit('error', err);
          ^
TypeError: Cannot read property 'req' of undefined
```

**Comment by kriskowal** [comment]
I suspect this is related to #249 (closed)

Perhaps this should be downgraded from a warning and augmented with a stat counter since multiple responses, particularly multiple error responses, are expected under normal operating conditions.

**Comment by Raynos** [comment]
This is the same error.

Except for incoming error frames; not for incoming error responses;
