### ISSUE TITLE
golang: init-handling error testing scenarios

### ISSUE THREAD

**Issue by mmihic** [uber/tchannel#279]
__client side__
- [ ] server returns unsupported protocol version
- [ ] server does not return supported headers
- [ ] server hangs up after we've sent the init-req
- [ ] server sends us a message before we've sent the init-req
- [ ] server sends something other than an init-res in response to our init-req
- [ ] server sends a protocol error in response to our init-req

__server side__
- [x] client sends an unsupported protocol version
- [x] client does not include supported headers
- [ ] client hangs up before we've sent the init-res
- [ ] client sends something other than an init-req as the first message
- [ ] client sends bad data on init-req

**Comment by jcorbin** [comment]
great idea, made #280 to track node similarly

**Comment by prashantv** [comment]
Migrated to https://github.com/uber/tchannel-go/issues/125
