### ISSUE TITLE
golang: tests for client-side error conditions

### ISSUE THREAD

**Issue by mmihic** [uber/tchannel#320]
All scenarios need to verify that the call is marked as error (all subsequent use returns the same error), all frames are released, response channels are closed, and message exchanges are released.  

- [ ] Send channel full during initial send. (results in ServerBusy)
- [ ] Send channel full during fragment send. (results in ServerBusy, call marked as error)
- [ ] Application calls WriteArg2 more than once
- [ ] Application calls WriteArg3 more than once.
- [ ] Application calls ReadArg2 more than once.
- [ ] Application calls ReadArg3 more than once.
- [ ] Server responds with bad CallRes
- [ ] Server responds with bad CallResContinue
- [ ] Server responds with Error frame instead of CallRes (already tested, but need to verify cleanup)
- [ ] Server responds with Error frame after initial CallRes
- [ ] Server responds with protocol Error frame on another concurrent request 
- [ ] Server violates protocol in some way (e.g. sends InitReq or InitRes)
- [ ] Server hangs up before sending initial CallRes
- [ ] Server hangs up after sending initial CallRes but before sending final CallResContinue
- [ ] Frame receiver cannot forward to response call channel (i.e. application has stopped reading fragments)

Below scenarios should fail before a call is allocated:
- [ ] Attempt to send request after current context deadline has elapsed
- [ ] Attempt to send request after current context has been cancelled
- [ ] Attempt to send request on uninitialized connection (not possible through visible api, but should cover with tests anyway)
- [ ] Attempt to send request on closed connection (not possible through visible api, but should covert with tests anyway)

**Comment by prashantv** [comment]
Migrated to https://github.com/uber/tchannel-go/issues/129
