### ISSUE TITLE
golang: tests for server side error conditions

### ISSUE THREAD

**Issue by mmihic** [uber/tchannel#321]
Similar cleanup expected as #320 

- [ ] Application calls ReadArg2 more than once
- [ ] Application calls ReadArg3 more than once
- [ ] Application calls WriteArg2 more than once
- [ ] Application calls WriteArg3 more than once
- [ ] TTL expires while application is waiting for a CalReqContinue fragment
- [ ] TTL expires, but application never performs another fragment read
- [ ] Client sends an unparseable CallReqContinue
- [ ] Client sends a protocol Error frame while one or more calls are outstanding.  All outstanding calls should be cancelled and cleaned up.
- [ ] Client violates protocol in some way (e.g. sends another InitReq, sends InitRes) while one or more cals are outstanding.
- [ ] FrameReceiver cannot send CallReqContinue to request channel (i.e. application stops reading and the channel fills up)

Following should result in an error / ignore before the inbound call is dispatched
- [ ] Client sends a CallResContinue for an id that is no longer active
- [ ] Client sends a CallReq whose id is the same as an already active call
- [ ] Client sends an unparseable CallReq
- [ ] CallReq arrives for already cancelled id.  This one is interesting due to potential for id wrapping.

**Comment by prashantv** [comment]
Migrated to https://github.com/uber/tchannel-go/issues/128
