### ISSUE TITLE
Name the arguments and responses.

### ISSUE THREAD

**Issue by lxe** [uber/tchannel#35]
What's the case agains actually naming the arguments ('name', 'head', 'body') in both `README.md` and the source, instead of using 'arg1', 'arg2', and 'arg3'?

**Comment by Raynos** [comment]
there was a PR for that change, was never merged. I'm :+1:

**Comment by jcorbin** [comment]
We've doubled down on calling them arg1, arg2, arg3 at lower level in v2, leaving any semantic meaning (such as "method", "head", "body") to what we're calling the "arg schema" to be implemented by another layer (vaguely called things like tchannel-as-{thrift,json,http}).
