### ISSUE TITLE
Allow listen() on port 0

### ISSUE THREAD

**Issue by abhinav** [uber/tchannel#402]
And automatically pick a port.

Right now the interface is repetitive for no reason:

    TChannel("localhost:9999").host(handler).listen(9999)

The latter mention of the port isn't necessary and the first one can automatically be picked if ignored.

Thoughts?
CC: @breerly @blampe @junchaowu

**Comment by junchaowu** [comment]
I think we need to support config port after user initialize tchannel. It is more flexible.

**Comment by abhinav** [comment]
The port won't change, though. It would be an optional argument at construction, but if you skip, we pick one automatically. Either way, you don't want to be able to change it later.

**Comment by breerly** [comment]
Should be optional. If not provided, we attempt to determine automatically, failing hard if we cannot.

**Comment by abhinav** [comment]
This was done in the peer management change. Resolving.
