### ISSUE TITLE
python: Declare exception types for different error frame types

### ISSUE THREAD

**Issue by abhinav** [uber/tchannel#403]
Currently if we want to send an error frame from inside a handler, we manually build an ErrorMessage object and call `connection.senderror`.

Ideally, the handler should just throw something like `BadRequest("Unsupported call")` which gets translated into a `ErrorMessage(ErrorCode.bad_request, "Unsupported call", messageId)` frame and sent over the wire.

CC @breerly @blampe @junchaowu

**Comment by junchaowu** [comment]
My thought on this is the response should have this extensibility to send error frame. In the streaming change, I have gradually changes the response in that direction

**Comment by abhinav** [comment]
no longer relevant
