### ISSUE TITLE
hyperbahn incoming socket advertisement

### ISSUE THREAD

**Issue by Raynos** [uber/tchannel#487]
When connecting and advertising to hyperbahn; The hyperbahn exit nodes will open an incoming connection to your tchannel peer.

The incoming connection is from hyperbahn if it sends you a `CallRequest` where `service` is `"hyperbahn"` and arg1 is `ad`.

i.e. hyperbahn will advertise that it is hyperbahn on any incoming connection it opens to you. This will only be done by hyperbahn exit nodes.

This is not currently implemented and will be done in the future.

cc: @abhinav @jcorbin

**Comment by abhinav** [comment]
Sounds good to me

**Comment by jcorbin** [comment]
arg2 and arg3 are defined to be empty[?.]

**Comment by Raynos** [comment]
Sorry; ill defined.

`arg2` is JSON currently; `arg3` is JSON currently.

`arg3` is `{ services: [{ cost: 0, service: 'hyperbahn' }] }`

The exit node will advertise that it has a hyperbahn service available at cost zero; this implies that you can advertise to and also send forwarding call requests to it.

**Comment by Raynos** [comment]
This will be punted until we move "ad" into tchannel for v3.
