### ISSUE TITLE
protocol: Consider adding ttl to cancel and claim frames

### ISSUE THREAD

**Issue by kriskowal** [uber/tchannel#502]
This would be necessary to collect tombstones after any subsequent corresponding request would be declined due to expiration.

**Comment by kriskowal** [comment]
cc @mranney @jcorbin @breerly

**Comment by breerly** [comment]
Either this or using the max ttl. If we think this optimization is worth having to send it, then let's do it.

**Comment by jcorbin** [comment]
Spoke with @mranney about this out of our morning sync, I'll be implementing this change today.

**Comment by mranney** [comment]
Yeah, I like adding ttl to claim/cancel.

**Comment by Raynos** [comment]
This is implemented.
