### ISSUE TITLE
node: Update examples to use ephemeral clients and explicit server addresses

### ISSUE THREAD

**Issue by kriskowal** [uber/tchannel#505]
From #270 

> listening on `0.0.0.0` is an anti pattern that we don't want to encourage, let's:
> - [ ] drop the `.listen()` from all example clients now that we have ephemeral semantics
> - [ ] use explicit IPs, either loopback or discovered, for example server

**Comment by Raynos** [comment]
Our examples use explicit IPs and do not listen on 0.0.0.0
