### ISSUE TITLE
Allow system to grant local port

### ISSUE THREAD

**Issue by kriskowal** [uber/tchannel#54]
I suspect TChannel should support the case where the server or client allows the operating system to assign a port instead of requiring the user to designate the desired port. This would involve listening on port 0 and catching the given port from serverSocket.address() in the listen event, and finishing initialization at that time.

Do the hostname and port need to be both assigned because the reverse lookup might not match serverSocket.address()?

**Comment by jcorbin** [comment]
I believe this was done, re-open with clarification if not.
