### ISSUE TITLE
Don't allow choosing peers that aren't yet identified

### ISSUE THREAD

**Issue by jcorbin** [uber/tchannel#555]
... but how will we then (re)connect to them.

**Comment by kriskowal** [comment]
#553 moves the health score function out of the peer state module and as shouldRequest on peer. The state machine has its own shouldRequest that conditionally consults the peer.shouldRequest. peer.shouldRequest internally initiates connections if they do not yet exist. That will need to be adjusted to return 0 if the peer is connected but not yet identified. Passing the hot potato to @ShanniLi.

**Comment by jcorbin** [comment]
Okay considering all of that then, let's not change peer choice logic for now.

Instead we'll change within `TChannelRequest#resend` around `.choosePeer`'s result.
