### ISSUE TITLE
tchannel/as/thrift should take a `thriftName` field on response

### ISSUE THREAD

**Issue by Raynos** [uber/tchannel#584]
We currently have this signature;

```js
function handler(opts, req, head, body, cb) {
  var err = new Error('my error');
  err.nameAsThrift = 'myError';
  cb(null, {
    ok: false,
    body: err
  });
}
```

We should move towards an interface like:

```js
function handler(opts, req, head, body, cb) {
  cb(null, {
    ok: false,
    thriftName: 'myError'
    body: new Error('my error')
  });
}
```

Open questions:

 - what do we call this field; `thriftName` ??
 - should we drop the `ok` field and infer it from the `thriftName` value (which could be the string "success").

cc @jcorbin @kriskowal

**Comment by kriskowal** [comment]
If we go this route, let’s call it "type". So instead of "ok: true, you'd "type": "success", or "type" is one of the named error cases.

**Comment by Raynos** [comment]
type might be confusing because `err.type` is a thing;

We may also want to keep the `ok` field as it drives the call response and it is used in other as handlers;

Having to set `thriftName: "success"` instead of `ok: true` bleeds a lot of internal implementation details of thrift. It's actually not documented in thrift that the field name for the return struct is called `"success"`, it's an implementation detail.

**Comment by Willyham** [comment]
I like this direction, and I think that we should keep passing `ok` rather than inferring from the name of the return struct. People call that all kinds of different things.

Another option, and I'm not sure how I really feel about this, is to provide an error constructor from the spec which has the 'thriftName` already set on it. This would mean that we'd need to quantify the error with the function name too, so it could look something like this:

```
function isHealthy(opts, req, head, body, cb) {
  var spec = opts.spec;
  cb(null, {
    ok: false,
    body: new spec.isHealthy.SomeError('foo')
  });
}

That would hide a lot of the weirdness of having to get the right thriftName from the implementor.

**Comment by Raynos** [comment]
@Willyham We considered the option of exposing error constructors on the spec.

The only issue there is; what if you want to return an error from a library that is thrift agnostic; you would have to either wrap or clone it. This proposal allows you to specify the thriftName field and pass through someone else's error.

For example a uniqueness constraint "validation" error coming from your database.

It might actually be better to wrap all errors in the handlers anyway.

**Comment by Willyham** [comment]
Yeah I feel like the responsibility of shape correctness is solely the handlers - I think wrapping the error would be fine. If I get the time, would either of you be opposed to a thriftify change to make this happen?

**Comment by Willyham** [comment]
@jcorbin Something to think about with your refactor too

**Comment by Raynos** [comment]
@willyham exposing error constructors on non-trivially nuanced.

**Comment by Raynos** [comment]
This is implemented.
