### ISSUE TITLE
Stat emitter interfaces

### ISSUE THREAD

**Issue by kriskowal** [uber/tchannel#596]
Need function to forward stats to Statsd (with tags flattened into name).

**Comment by Raynos** [comment]
:+1: 

Ideally we add `opts.statsd` to `TChannel({ ... })` and if statsd is given we `hookupStatsd(self.statEvent, opts.statsd)`

**Comment by Raynos** [comment]
This is done in autobahn. needs to be ported here.

**Comment by Raynos** [comment]
This is implemented.
