### ISSUE TITLE
Node: support per request time out.

### ISSUE THREAD

**Issue by Raynos** [uber/tchannel#607]

**Comment by Raynos** [comment]
Ncar wants three retries with 30s delay each.

**Comment by jcorbin** [comment]
We do support per-request timeout at the channel level.  Specifying a static per-attempt timeout seems an anti-pattern to me, and I'd outright label ncar's "want" for it an artifact of prior behavior that should be changed.

**Comment by Raynos** [comment]
@jcorbin 

This is a temporary feature we want ahead of specatilive execution.

The semantics we want is for a single instance to waste the entire timeout. 

I.e. To avoid implementing retries at the application layer I want to say "1000 ttl; at least three instances attempted"

Basically I want to retry on timeouts. Which happen a lot because lol spikes of 100% cpu

**Comment by Raynos** [comment]
Implemented.
