### ISSUE TITLE
tracing header.

### ISSUE THREAD

**Issue by Raynos** [uber/tchannel#93]
Because node has poor support for int64 we need to work around this.

I audited a few modules
 
 - int64 ( https://github.com/broofa/node-int64 )
 - long ( https://github.com/dcodeIO/Long.js )

Having looked at int64, it is too easy to treat it as a "number" and accidentally lose precision.

Having looked at long it's basically  { lo: int32, hi: int32 } with a ton of helper methods and is not very `Buffer` friendly. It has a bunch of string and math helper functions in it that may or may not be useful.

For our needs we should see if we can get away with just returning an 8 byte buffer for `int64`. If we need to do any manipulation on it we can `.readUInt32BE(0)` and `.readUInt32BE(4)` to get the low and high int32 out of it. 

If we find the node implementation needs to do a lot of manipulation of this data we might want to import a module like `long` to do maths on it.

**Comment by jcorbin** [comment]
Yeah I don't know why we can't just use 8 byte buffers

**Comment by Raynos** [comment]
:+1: for 8 byte buffers. Looking at prior art most other systems return "bignum" or "int64" constructors. 

I think we should ignore those things and stick to 8 byte buffers and cast the 4 byte buffers into javascript numbers.

**Comment by jcorbin** [comment]
has been implemented using 8-byte buffers
