### ISSUE TITLE
consolidating documentation

### ISSUE THREAD

**Issue by blampe** [uber/tchannel#934]
I'd like to propose that we repurpose tchannel.readthedocs.org for high-level TChannel documentation like the protocol, metrics, etc., which are very painful to read on github. Readthedocs supports subprojects, so this can also serve as a landing page to tchannel.readthedocs.org/projects/python, tchannel.readthedocs.org/projects/node, etc.

tchannel.readthedocs.org is currently running outdated Python docs, which have moved to tchannel-python.readthedocs.org. @sectioneight I think you need to add some of us as maintainers on readthedocs so we can start making these changes.

cc @Raynos @jcorbin

**Comment by Raynos** [comment]
I don't mind where we host docs. 

Personally I like reading markdown through the github UI, as long as the docs stay in markdown in the source code and readthedocs is just a pretty GUI then I dont care.

Removing the documentation from tchannel would be bad.

**Comment by prashantv** [comment]
Is readthedocs supposed to be for API documentation or for guides? API
documentation for go tends to live on godoc.org. e.g.
http://godoc.org/github.com/uber/tchannel/golang

Which is automatically generated from the source code. I'm happy to put the
guides up there and point to the godoc for the full API documentation.

**Comment by sectioneight** [comment]
@blampe i added "blampe" as a maintainer on readthedocs. If that's not you, or if there are other people I should add, please let me know the names here

**Comment by blampe** [comment]
tchannel.readthedocs.org

@prashantv I agree golang api docs should continue to live on godoc.org. Take a look at how things are laid out right now. Maybe we should include direct links to every language's guide?
