### ISSUE TITLE
Consider using `duplexer2` for handler.

### ISSUE THREAD

**Issue by Raynos** [uber/tchannel#98]
This would allow you to have a public `.write()` so you can pipe frames into the handler and have an internal `.write()` to do flush notifications.

Duplexer2 turns { in: duplex, out: duplex } into duplex and wires `in.write()` and `out.read()` up, allowing you to do `in.on('data')` and `out.write()` internally.

This means you can use the `out.write(chunk, cb)` pattern to get flushing notifications for sending frames out but still have `reader.pipe(handler).pipe(writer)`

**Comment by jcorbin** [comment]
One of the concrete benefits to doing this would be to defer inOps mutation like we used to before #95 until after we've confirmed frame flush outside of node process.

**Comment by Raynos** [comment]
Cannot use streams for handlers as it is a significant performance hit.
